In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("very_unclean_student_dataset.csv")
df

student_id         student_name     father_name   gender     age  class  \
0           NaN    Denise Anderson               NaN     Male     200    NaN   
1             2   Christopher Turner      Gary Davis  unknown      22  BS-CS   
2             3                  NaN             NaN      NaN      17    NaN   
3          ID_3                  NaN         unknown        M      -5   10th   
4          ID_4        Kelsey Harper  Maria Lewis123      NaN      27  bs-cs   
...         ...                  ...             ...      ...     ...    ...   
3045       1155                  NaN             NaN      NaN      24    NaN   
3046        888                  NaN         unknown     Male      -5    NaN   
3047        NaN                  NaN             NaN     Male     NaN    NaN   
3048       2062         JULIA THOMAS  Jack Fisher123   Female  twenty   BSCS   
3049        NaN        aaron wiggins             NaN      NaN      -5    NaN   

     python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0             NaN         NaN     absent        NaN       NaN   
1             NaN         NaN         17       31.0       NaN   
2          eighty         NaN         58        NaN       149   
3          eighty         NaN          8        NaN       NaN   
4          eighty         NaN     absent        NaN       150   
...           ...         ...        ...        ...       ...   
3045          NaN        33.0     absent        NaN         ?   
3046          115        90.0        NaN       30.0         ?   
3047       eighty         NaN        NaN        NaN       -31   
3048           38        97.0     absent        NaN         ?   
3049          NaN         NaN     absent        NaN        36   

                 city     admission_date  
0             123City  December 02, 2024  
1                 NaN         06/05/2022  
2     LAKE SONYAMOUTH     March 11, 2024  
3                 NaN         1994-09-06  
4           Gouldside         06/12/2021  
...               ...                ...  
3045          123City         not_a_date  
3046          123City                NaN  
3047              NaN         2026.01.29  
3048              NaN         2005-10-10  
3049  PORT APRILSHIRE         09/05/2023  

[3050 rows x 13 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   student_id      2287 non-null   object 
 1   student_name    2049 non-null   object 
 2   father_name     2446 non-null   object 
 3   gender          2219 non-null   object 
 4   age             2376 non-null   object 
 5   class           2297 non-null   object 
 6   python_marks    1550 non-null   object 
 7   java_marks      1508 non-null   float64
 8   ruby_marks      2029 non-null   object 
 9   cpp_marks       1030 non-null   float64
 10  sql_marks       2087 non-null   object 
 11  city            1834 non-null   object 
 12  admission_date  2562 non-null   object 
dtypes: float64(2), object(11)
memory usage: 309.9+ KB


In [7]:
df.columns

Index(['student_id', 'student_name', 'father_name', 'gender', 'age', 'class',
       'python_marks', 'java_marks', 'ruby_marks', 'cpp_marks', 'sql_marks',
       'city', 'admission_date'],
      dtype='object')

## Cleaning column names

In [8]:
df.columns = (df.columns.astype(str).str.strip().str.lower().str.replace(" ", "_").str.replace(r"[^\w]","", regex = True))
df.columns

Index(['student_id', 'student_name', 'father_name', 'gender', 'age', 'class',
       'python_marks', 'java_marks', 'ruby_marks', 'cpp_marks', 'sql_marks',
       'city', 'admission_date'],
      dtype='object')

## Cleaning Categorical Columns

In [9]:
df[["student_name", "father_name", "gender", "city"]] = (
    df[["student_name", "father_name", "gender", "city"]].astype(str).apply(lambda x: x.str.lower().str.strip()))

In [10]:
df

student_id        student_name     father_name   gender     age  class  \
0           NaN     denise anderson             nan     male     200    NaN   
1             2  christopher turner      gary davis  unknown      22  BS-CS   
2             3                 nan             nan      nan      17    NaN   
3          ID_3                 nan         unknown        m      -5   10th   
4          ID_4       kelsey harper  maria lewis123      nan      27  bs-cs   
...         ...                 ...             ...      ...     ...    ...   
3045       1155                 nan             nan      nan      24    NaN   
3046        888                 nan         unknown     male      -5    NaN   
3047        NaN                 nan             nan     male     NaN    NaN   
3048       2062        julia thomas  jack fisher123   female  twenty   BSCS   
3049        NaN       aaron wiggins             nan      nan      -5    NaN   

     python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0             NaN         NaN     absent        NaN       NaN   
1             NaN         NaN         17       31.0       NaN   
2          eighty         NaN         58        NaN       149   
3          eighty         NaN          8        NaN       NaN   
4          eighty         NaN     absent        NaN       150   
...           ...         ...        ...        ...       ...   
3045          NaN        33.0     absent        NaN         ?   
3046          115        90.0        NaN       30.0         ?   
3047       eighty         NaN        NaN        NaN       -31   
3048           38        97.0     absent        NaN         ?   
3049          NaN         NaN     absent        NaN        36   

                 city     admission_date  
0             123city  December 02, 2024  
1                 nan         06/05/2022  
2     lake sonyamouth     March 11, 2024  
3                 nan         1994-09-06  
4           gouldside         06/12/2021  
...               ...                ...  
3045          123city         not_a_date  
3046          123city                NaN  
3047              nan         2026.01.29  
3048              nan         2005-10-10  
3049  port aprilshire         09/05/2023  

[3050 rows x 13 columns]

In [11]:
df["student_name"].value_counts()

student_name
nan                1001
james jackson         3
heather miller        3
david bailey          2
adrian mejia          2
                   ... 
ryan dawson           1
tiffany larson        1
stacy alvarado        1
pamela bartlett       1
lauren gilbert        1
Name: count, Length: 1991, dtype: int64

In [12]:
df[df["student_name"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

## Drop Duplicated Values

In [13]:
df.duplicated().sum()

np.int64(50)

In [14]:
df[(df.duplicated())]

student_id              student_name            father_name   gender  \
3000        539                       nan                    nan        f   
3001        NaN               kevin jones   katherine washington   female   
3002        243               ryan wilcox                    nan      nan   
3003       1175               colin welch        karen taylor123     male   
3004        NaN             anthony smith          susan calhoun     male   
3005       2541            crystal dunlap         jeffrey vargas     male   
3006        357                amy powell          sarah navarro        m   
3007       1500          stephen richmond                    nan   female   
3008        703               kyle wilson                unknown   female   
3009        NaN                       nan            kara morgan     male   
3010        NaN            michelle henry                    nan        m   
3011    ID_2743               tracey kane                    nan     male   
3012    ID_2862                       nan                unknown     male   
3013        478       sally nicholson dds                unknown  unknown   
3014        NaN                       nan                unknown   female   
3015       1182                       nan                unknown     male   
3016        NaN          mitchell schmidt                    nan      nan   
3017        NaN              zachary rios          cynthia hicks     male   
3018    ID_1984             cynthia scott                unknown     male   
3019       2713                    ann yu             jason sosa        m   
3020    ID_1161                       nan          justin graves     male   
3021        895                       nan         linda craig123        m   
3022     ID_579               erika greer             juan lloyd     male   
3023        623                       nan                unknown        m   
3024        NaN                karen koch                    nan        f   
3025    ID_2458            angela escobar                unknown        m   
3026       1969  mrs. tiffany santana dvm          isaiah kim123     male   
3027     ID_191           tonya fernandez          troy thornton      nan   
3028       2515               noah flores        robert santiago        f   
3029        NaN         jonathan gonzales                    nan        m   
3030       1790         abigail hernandez            cindy young        m   
3031       2188                       nan                    nan      nan   
3032     ID_150                       nan     elizabeth mayer123     male   
3033        NaN                       nan         craig castillo        m   
3034        NaN             jennifer ford          tamara barnes  unknown   
3035       1603                       nan        stephanie stone     male   
3036        382            amanda russell                unknown        f   
3037        922                       nan         rebecca brooks      nan   
3038        NaN           laura castaneda  christina alvarado123      nan   
3039        NaN               kayla singh                unknown  unknown   
3040     ID_139                       nan          michael young  unknown   
3041        168           candice shelton                unknown     male   
3042        NaN           thomas williams                unknown     male   
3043    ID_1702          catherine tanner       daniel gillespie      nan   
3044        NaN              adrian mejia                unknown   female   
3045       1155                       nan                    nan      nan   
3046        888                       nan                unknown     male   
3047        NaN                       nan                    nan     male   
3048       2062              julia thomas         jack fisher123   female   
3049        NaN             aaron wiggins                    nan      nan   

         age  class python_marks  java_marks ruby_marks  cpp_marks sql_marks 

In [15]:
df.drop_duplicates(inplace = True)

In [16]:
df

student_id        student_name         father_name   gender     age  \
0           NaN     denise anderson                 nan     male     200   
1             2  christopher turner          gary davis  unknown      22   
2             3                 nan                 nan      nan      17   
3          ID_3                 nan             unknown        m      -5   
4          ID_4       kelsey harper      maria lewis123      nan      27   
...         ...                 ...                 ...      ...     ...   
2995       2996          kari haley                 nan      nan     200   
2996    ID_2996                 nan             unknown  unknown  twenty   
2997       2998                 nan  matthew johnson123  unknown      21   
2998       2999      carol mitchell       robin hawkins   female      -5   
2999       3000      lauren gilbert             unknown        m     NaN   

      class python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0       NaN          NaN         NaN     absent        NaN       NaN   
1     BS-CS          NaN         NaN         17       31.0       NaN   
2       NaN       eighty         NaN         58        NaN       149   
3      10th       eighty         NaN          8        NaN       NaN   
4     bs-cs       eighty         NaN     absent        NaN       150   
...     ...          ...         ...        ...        ...       ...   
2995  BS-CS           54        51.0         28        NaN         ?   
2996    NaN       eighty         NaN     absent       82.0        24   
2997  bs-cs           68        90.0        NaN        NaN       NaN   
2998   10th           82         NaN        NaN        NaN         ?   
2999  BS-CS          NaN         NaN         78       82.0         ?   

                 city     admission_date  
0             123city  December 02, 2024  
1                 nan         06/05/2022  
2     lake sonyamouth     March 11, 2024  
3                 nan         1994-09-06  
4           gouldside         06/12/2021  
...               ...                ...  
2995              nan         2023.09.03  
2996   east kellybury         not_a_date  
2997   west susanberg    August 06, 2023  
2998              nan         11/05/2025  
2999     dixonborough                NaN  

[3000 rows x 13 columns]

In [17]:
df.duplicated().sum()

np.int64(0)

## Cleaning Student Id column

In [18]:
df["student_id"] = list(df.index)
df

student_id        student_name         father_name   gender     age  \
0              0     denise anderson                 nan     male     200   
1              1  christopher turner          gary davis  unknown      22   
2              2                 nan                 nan      nan      17   
3              3                 nan             unknown        m      -5   
4              4       kelsey harper      maria lewis123      nan      27   
...          ...                 ...                 ...      ...     ...   
2995        2995          kari haley                 nan      nan     200   
2996        2996                 nan             unknown  unknown  twenty   
2997        2997                 nan  matthew johnson123  unknown      21   
2998        2998      carol mitchell       robin hawkins   female      -5   
2999        2999      lauren gilbert             unknown        m     NaN   

      class python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0       NaN          NaN         NaN     absent        NaN       NaN   
1     BS-CS          NaN         NaN         17       31.0       NaN   
2       NaN       eighty         NaN         58        NaN       149   
3      10th       eighty         NaN          8        NaN       NaN   
4     bs-cs       eighty         NaN     absent        NaN       150   
...     ...          ...         ...        ...        ...       ...   
2995  BS-CS           54        51.0         28        NaN         ?   
2996    NaN       eighty         NaN     absent       82.0        24   
2997  bs-cs           68        90.0        NaN        NaN       NaN   
2998   10th           82         NaN        NaN        NaN         ?   
2999  BS-CS          NaN         NaN         78       82.0         ?   

                 city     admission_date  
0             123city  December 02, 2024  
1                 nan         06/05/2022  
2     lake sonyamouth     March 11, 2024  
3                 nan         1994-09-06  
4           gouldside         06/12/2021  
...               ...                ...  
2995              nan         2023.09.03  
2996   east kellybury         not_a_date  
2997   west susanberg    August 06, 2023  
2998              nan         11/05/2025  
2999     dixonborough                NaN  

[3000 rows x 13 columns]

## Cleaning student name column

In [19]:
df = df[~((df["student_name"] == "nan") & (df["father_name"] == "nan"))]

In [20]:
df

student_id        student_name         father_name   gender     age  \
0              0     denise anderson                 nan     male     200   
1              1  christopher turner          gary davis  unknown      22   
3              3                 nan             unknown        m      -5   
4              4       kelsey harper      maria lewis123      nan      27   
5              5       tabitha payne                 nan        f      -5   
...          ...                 ...                 ...      ...     ...   
2995        2995          kari haley                 nan      nan     200   
2996        2996                 nan             unknown  unknown  twenty   
2997        2997                 nan  matthew johnson123  unknown      21   
2998        2998      carol mitchell       robin hawkins   female      -5   
2999        2999      lauren gilbert             unknown        m     NaN   

      class python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0       NaN          NaN         NaN     absent        NaN       NaN   
1     BS-CS          NaN         NaN         17       31.0       NaN   
3      10th       eighty         NaN          8        NaN       NaN   
4     bs-cs       eighty         NaN     absent        NaN       150   
5       NaN          NaN         NaN        NaN        NaN        99   
...     ...          ...         ...        ...        ...       ...   
2995  BS-CS           54        51.0         28        NaN         ?   
2996    NaN       eighty         NaN     absent       82.0        24   
2997  bs-cs           68        90.0        NaN        NaN       NaN   
2998   10th           82         NaN        NaN        NaN         ?   
2999  BS-CS          NaN         NaN         78       82.0         ?   

                city     admission_date  
0            123city  December 02, 2024  
1                nan         06/05/2022  
3                nan         1994-09-06  
4          gouldside         06/12/2021  
5                nan                NaN  
...              ...                ...  
2995             nan         2023.09.03  
2996  east kellybury         not_a_date  
2997  west susanberg    August 06, 2023  
2998             nan         11/05/2025  
2999    dixonborough                NaN  

[2815 rows x 13 columns]

In [21]:
if "student_name" in df.columns:
    df.loc[df["student_name"] == "nan", "student_name"] = np.nan
    df["student_name"] = df["student_name"].fillna("unknown")

df

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\860209168.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["student_name"] = df["student_name"].fillna("unknown")


student_id        student_name         father_name   gender     age  \
0              0     denise anderson                 nan     male     200   
1              1  christopher turner          gary davis  unknown      22   
3              3             unknown             unknown        m      -5   
4              4       kelsey harper      maria lewis123      nan      27   
5              5       tabitha payne                 nan        f      -5   
...          ...                 ...                 ...      ...     ...   
2995        2995          kari haley                 nan      nan     200   
2996        2996             unknown             unknown  unknown  twenty   
2997        2997             unknown  matthew johnson123  unknown      21   
2998        2998      carol mitchell       robin hawkins   female      -5   
2999        2999      lauren gilbert             unknown        m     NaN   

      class python_marks  java_marks ruby_marks  cpp_marks sql_marks  \
0       NaN          NaN         NaN     absent        NaN       NaN   
1     BS-CS          NaN         NaN         17       31.0       NaN   
3      10th       eighty         NaN          8        NaN       NaN   
4     bs-cs       eighty         NaN     absent        NaN       150   
5       NaN          NaN         NaN        NaN        NaN        99   
...     ...          ...         ...        ...        ...       ...   
2995  BS-CS           54        51.0         28        NaN         ?   
2996    NaN       eighty         NaN     absent       82.0        24   
2997  bs-cs           68        90.0        NaN        NaN       NaN   
2998   10th           82         NaN        NaN        NaN         ?   
2999  BS-CS          NaN         NaN         78       82.0         ?   

                city     admission_date  
0            123city  December 02, 2024  
1                nan         06/05/2022  
3                nan         1994-09-06  
4          gouldside         06/12/2021  
5                nan                NaN  
...              ...                ...  
2995             nan         2023.09.03  
2996  east kellybury         not_a_date  
2997  west susanberg    August 06, 2023  
2998             nan         11/05/2025  
2999    dixonborough                NaN  

[2815 rows x 13 columns]

In [22]:
import re

def remove_titles(name):
    name = name.strip().lower()
    
    # Remove prefix titles
    name = re.sub(r'^(mr|mrs|ms|dr|miss)\.\s*', '', name)
    
    # Remove suffix titles
    name = re.sub(r'\s+(md|dds|dvm|phd|jr\.?|iii)$', '', name)
    
    return name.strip()

df["student_name"] = df["student_name"].apply(remove_titles)

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\409956968.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["student_name"] = df["student_name"].apply(remove_titles)


In [23]:
for name in df["student_name"].unique():
    print(name)

denise anderson
christopher turner
unknown
kelsey harper
tabitha payne
crystal cox
steven daniels
hector reyes
karen koch
lori colon
kathryn meyer
manuel sutton
laura ferrell
steven camacho
felicia jackson
rebecca walter
michael chapman
jordan jordan
miguel sharp
kenneth mcclure
justin turner
chad brown
susan cruz
veronica harmon
karen diaz
emily franklin
victoria park
robert jenkins
timothy adams
nicolas pierce
julie davis
christopher robles
andrew morton
kristine harris
kara grant
julie hunter
becky navarro
valerie jones
jessica cline
crystal elliott
corey wilson
kelly goodwin
heather miller
aaron morgan
larry benitez
vanessa flores
tonya smith
rachel johns
heather wade
kayla dixon
marvin cox
michelle williams
matthew mcdonald
lisa hahn
david acosta
amanda khan
tyler elliott
sara barnes
jessica baker
kirk garcia
david woods
daniel moore
kelly jackson
james huff
chad knight
kayla lloyd
kari foster
chad brooks
jasmine middleton
nathan shelton
david collins
rhonda james
mark lewis
donna

## Cleaning Father name column

In [24]:

for name in df["father_name"].unique():
    print(name)

nan
gary davis
unknown
maria lewis123
jonathan wilson123
james grant
david sanchez
stacy smith
timothy cox123
kathryn lee
scott simon123
patrick simmons
kara morgan
robin hunt123
steven peters123
tara ford
benjamin rodriguez
paul phillips
sharon holland
joy pennington
whitney mckay123
richard davis
peggy lewis
rodney anderson
donald tyler
shane black
karen wilson
jeremiah adams
brian peterson123
alexandra cisneros
alicia gonzales123
michael rivers
karen palmer123
sean sanchez
michael jordan
charlene hamilton123
jorge edwards123
ann hood
juan haley123
christopher rodriguez
travis combs
mario reynolds
howard rivera jr.
meghan acevedo
christine arellano
jay stewart
erin frost
benjamin gentry123
derek frazier
eric esparza
cheryl graham
meghan mendoza123
robert may
benjamin beck
brandi wood123
terri wright123
kayla walters
dylan ryan123
david davis123
ariana gillespie123
laura salas
dr. steven rodriguez
justin nelson
nancy pearson
david wyatt123
frank howell123
rachel murray
robert scott123

In [25]:
df["father_name"] = df["father_name"].replace("unknown", np.nan)

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\4123179938.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["father_name"] = df["father_name"].replace("unknown", np.nan)


In [26]:
df[df["father_name"] == "unknown"]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [27]:
df["father_name"] = df["father_name"].fillna("ffill")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\336137975.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["father_name"] = df["father_name"].fillna("ffill")


In [172]:

to_fill = ["gary davis", "robin hawkins", "joyce hale", "nancy wheeler"]
unwanted = ["ffill"]

mask = df["father_name"].isin(unwanted)
df.loc[mask, "father_name"] = np.resize(to_fill, mask.sum())

In [173]:
df["father_name"].isnull().sum()

np.int64(0)

## Mapping Gender Column

In [29]:
df["gender"].unique()

array(['male', 'unknown', 'm', 'nan', 'f', 'female'], dtype=object)

In [30]:
df[df["student_name"] == 20] 

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [31]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [32]:
gender_map = {
    "m" : "male",
    "M" : "male",
    "male" : "male",
    "f" : "female",
    "F" : "female",
    "female" : "female"
}

df["gender"] = df["gender"].map(gender_map).fillna("unknown")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\3014665566.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gender"] = df["gender"].map(gender_map).fillna("unknown")


In [33]:
df.head()

student_id        student_name     father_name   gender  age  class  \
0           0     denise anderson             nan     male  200    NaN   
1           1  christopher turner      gary davis  unknown   22  BS-CS   
3           3             unknown           ffill     male   -5   10th   
4           4       kelsey harper  maria lewis123  unknown   27  bs-cs   
5           5       tabitha payne             nan   female   -5    NaN   

  python_marks  java_marks ruby_marks  cpp_marks sql_marks       city  \
0          NaN         NaN     absent        NaN       NaN    123city   
1          NaN         NaN         17       31.0       NaN        nan   
3       eighty         NaN          8        NaN       NaN        nan   
4       eighty         NaN     absent        NaN       150  gouldside   
5          NaN         NaN        NaN        NaN        99        nan   

      admission_date  
0  December 02, 2024  
1         06/05/2022  
3         1994-09-06  
4         06/12/2021  
5                NaN

In [34]:
df["gender"].unique()

array(['male', 'unknown', 'female'], dtype=object)

## Filling Age Column

In [35]:
df["age"].unique()

array(['200', '22', '-5', '27', 'twenty', nan, '19', '26', '15', '25',
       '30', '20', '16', '21', '17', '24', '23', '18', '28', '29'],
      dtype=object)

In [36]:
df["age"] = pd.to_numeric(df["age"], errors = "coerce")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\2325699403.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age"] = pd.to_numeric(df["age"], errors = "coerce")


In [37]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [38]:
if "age" in df.columns:
    df.loc[df["age"] == "twenty", "age"] = 20

In [39]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [40]:
df["age"].unique()

array([200.,  22.,  -5.,  27.,  nan,  19.,  26.,  15.,  25.,  30.,  20.,
        16.,  21.,  17.,  24.,  23.,  18.,  28.,  29.])

In [41]:
df[df["student_name"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [42]:
if "age" in df.columns:
    df.loc[df["age"] < 0 , "age"] = np.nan
    df["age"] = df["age"].fillna(df["age"].median())

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\3846272882.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age"] = df["age"].fillna(df["age"].median())


In [43]:
df["age"].unique()

array([200.,  22.,  27.,  19.,  26.,  15.,  25.,  30.,  20.,  16.,  21.,
        17.,  24.,  23.,  18.,  28.,  29.])

In [44]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [45]:
df["age"].value_counts()

age
200.0    2278
20.0       48
27.0       39
30.0       38
15.0       36
21.0       36
24.0       36
16.0       35
19.0       33
28.0       32
29.0       32
17.0       31
23.0       31
18.0       31
25.0       30
22.0       28
26.0       21
Name: count, dtype: int64

## Handling Class Column

In [46]:
df["class"].unique()

array([nan, 'BS-CS', '10th', 'bs-cs', 'BSCS', '12th', '11th'],
      dtype=object)

In [47]:
df["class"].value_counts()

class
10th     387
bs-cs    369
BSCS     353
BS-CS    352
12th     334
11th     325
Name: count, dtype: int64

In [48]:
df["class"] = (df["class"].astype(object).str.lower().str.strip().replace("-"," ",regex = False))

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\3310699237.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["class"] = (df["class"].astype(object).str.lower().str.strip().replace("-"," ",regex = False))


In [49]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [50]:
df["class"].unique()

array([nan, 'bs-cs', '10th', 'bscs', '12th', '11th'], dtype=object)

In [51]:
class_map = {
    "bs-cs" : "bscs",
    "bscs" : "bscs",
    "10th" : "10th",
    "11th" : "11th", 
    "12th" : "12th"
}

df["class"] = df["class"].map(class_map)

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\1712340100.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["class"] = df["class"].map(class_map)


In [52]:
df["class"] = (df["class"].replace("nan", np.nan).ffill().bfill())

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\1771988910.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["class"] = (df["class"].replace("nan", np.nan).ffill().bfill())


In [53]:
df["class"].unique()

array(['bscs', '10th', '12th', '11th'], dtype=object)

## Handling Python Columns

In [54]:
df["python_marks"].unique()

array([nan, 'eighty', '42', '90', '115', '113', '-16', '91', '36', '34',
       '20', '44', '66', '59', '51', '8', '33', '4', '79', '119', '67',
       '37', '-3', '32', '118', '84', '21', '31', '15', '58', '9', '-15',
       '41', '12', '49', '46', '28', '53', '50', '57', '27', '88', '100',
       '7', '-18', '0', '69', '104', '105', '-14', '54', '117', '83',
       '78', '65', '103', '30', '-2', '111', '106', '-4', '-11', '17',
       '-5', '23', '19', '87', '94', '18', '108', '82', '70', '38', '102',
       '89', '6', '43', '1', '75', '64', '96', '74', '47', '26', '39',
       '55', '85', '-20', '81', '80', '112', '45', '5', '-6', '71', '98',
       '10', '24', '-19', '-9', '76', '99', '11', '86', '60', '16', '29',
       '-12', '22', '-1', '-7', '-17', '48', '73', '92', '35', '120',
       '14', '101', '2', '61', '93', '62', '-13', '56', '25', '63', '97',
       '109', '116', '13', '95', '-8', '72', '114', '77', '107', '-10',
       '52', '68', '40', '3'], dtype=object)

In [55]:
if "python_marks" in df.columns:
    df.loc[df["python_marks"] == "eighty", "python_marks"] = 80

In [58]:
df["python_marks"] = pd.to_numeric(df["python_marks"], errors = "coerce")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\2922776882.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["python_marks"] = pd.to_numeric(df["python_marks"], errors = "coerce")


In [59]:
if "python_marks" in df.columns:
    df.loc[df["python_marks"] < 0, "python_marks"] = np.nan

In [60]:
num = [65, 55, 54, 76, 45, 59, 72, 75, 85]

py_mask = (df["python_marks"] > 100) | (df["python_marks"].isna())
count = py_mask.sum()

repeated_nums = np.resize(num, count)

df.loc[py_mask, "python_marks"] = repeated_nums

In [61]:
df["python_marks"].unique()

array([ 65.,  55.,  80.,  54.,  76.,  45.,  59.,  42.,  72.,  90.,  75.,
        85.,  91.,  36.,  34.,  20.,  44.,  66.,  51.,   8.,  33.,   4.,
        79.,  67.,  37.,  32.,  84.,  21.,  31.,  15.,  58.,   9.,  41.,
        12.,  49.,  46.,  28.,  53.,  50.,  57.,  27.,  88., 100.,   7.,
         0.,  69.,  83.,  78.,  30.,  17.,  23.,  19.,  87.,  94.,  18.,
        82.,  70.,  38.,  89.,   6.,  43.,   1.,  64.,  96.,  74.,  47.,
        26.,  39.,  81.,   5.,  71.,  98.,  10.,  24.,  99.,  11.,  86.,
        60.,  16.,  29.,  22.,  48.,  73.,  92.,  35.,  14.,   2.,  61.,
        93.,  62.,  56.,  25.,  63.,  97.,  13.,  95.,  77.,  52.,  68.,
        40.,   3.])

## Handling Java marks

In [62]:
df["java_marks"].unique()

array([ nan,  90.,  49.,  33., 127.,   0.,  26.,  -1., 104.,  48.,   1.,
        -4., 119.,  38.,  59.,  62.,  61.,  29.,  50.,  72.,  98.,  36.,
        24.,   7.,  35., 125.,  66., 107.,  64., 116.,   5.,  93., 115.,
       126.,  39.,  12.,  42.,  41., 124.,  21.,  51., 113., 114., 100.,
       129.,  25.,  94., 130.,  11.,  -9., 121.,  55.,  52.,  81., 106.,
        71.,  32.,  47.,  60.,  97.,  -2.,  -5., 109.,  74.,   6.,  57.,
         2.,  69.,   4., 123.,  86.,  91.,  13.,   8.,   9.,  43., 103.,
        -6.,  78., 111., 108., 112.,  20.,  15.,  -8.,  14.,  77.,  53.,
        58.,  88.,  -3.,  68.,  80.,  16., 120., 118.,  10.,  92.,  96.,
        85.,  31.,  44.,  84., 102.,  22.,  27.,  79.,  28., 128., 122.,
        82.,  75.,  45.,  18.,  -7.,  87.,  34.,  65.,  83.,  63.,  17.,
        37.,  70.,  54., 117.,  95.,  56.,  30.,  46.,  89.,  76., 101.,
        40., 110.,  23., 105.,   3.,  19.,  73.,  99.])

In [69]:
if "java_marks" in df.columns:
    df.loc[df["java_marks"] < 0, "java_marks"] = np.nan

In [83]:
num = [65, 55, 54, 76, 45, 59, 72, 75, 85]

java_mask = (df["java_marks"] > 100) | (df["java_marks"].isna())
count = java_mask.sum()

repeated_nums = np.resize(num, count)

df.loc[java_mask, "java_marks"] = repeated_nums

In [84]:
df["java_marks"].unique()

array([  0.,  44.,  54.,  74.,  90.,  33.,  84.,  26.,  64.,  34.,  48.,
         1.,  38.,  59.,  62.,  50.,  72.,   7.,   5.,  42.,  21., 100.,
        61.,  25.,  94.,  11.,  52.,  81.,  12.,  71.,  93.,  35.,  60.,
        97.,   2.,  69.,   4.,  86.,  91.,   8.,  43.,  98.,  78.,  66.,
        15.,  77.,  53.,  88.,  80.,  32.,  16.,  10.,  92.,  96.,  39.,
        68.,  47.,  22.,  27.,  13.,  45.,  18.,  87.,  28.,  75.,  63.,
        17.,  70.,  95.,  20.,  56.,  79.,  31.,  46.,  89.,  76.,  29.,
        85.,  24.,  23.,  58.,  83.,   3.,  19.,  82.,   9.,  57.,  41.,
        51.,  49.,  37.,  73.,   6.,  55.,  30.,  40.,  99.,  65.])

## Handling Ruby 

In [85]:
df["ruby_marks"].dtypes

dtype('float64')

In [86]:
if "ruby_marks" in df.columns:
    df.loc[df["ruby_marks"] == "absent", "ruby_marks"] = 0

In [87]:
df["ruby_marks"] = pd.to_numeric(df["ruby_marks"], errors = "coerce")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\1070911800.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ruby_marks"] = pd.to_numeric(df["ruby_marks"], errors = "coerce")


In [88]:
if "ruby_marks" in df.columns:
    df.loc[df["ruby_marks"] < 0, "ruby_marks"] = np.nan

In [89]:
num = [65, 55, 54, 76, 45, 59, 72, 75, 85]

ruby_mask = (df["ruby_marks"] > 100) | (df["ruby_marks"].isna())
count = ruby_mask.sum()

repeated_nums = np.resize(num, count)

df.loc[ruby_mask, "ruby_marks"] = repeated_nums

In [91]:
df["ruby_marks"].unique()

array([  0.,  17.,   8.,  65.,  43.,  55.,   6.,  54.,  76.,  45.,  78.,
        13.,  34.,  59.,  58.,  72.,  69.,  75.,  52.,  39.,  85.,  31.,
        32.,  97.,  71.,  79.,  68., 100.,  57.,  61.,  82.,  28.,  92.,
         9.,  22.,  83.,  86.,  26.,  99.,  51.,  44.,  66.,  11.,  60.,
        98.,  42.,  93.,  70.,  12.,  84.,  10.,  74.,  24.,  16.,   1.,
         2.,  25.,  80.,  23.,  50.,  41.,  35.,  36.,  63.,  37.,  40.,
        94.,  95.,  48.,  81.,  33.,  29.,  62.,  96.,  77.,  87.,  73.,
        19.,  89.,   3.,  21.,  53.,  64.,  14.,  46.,   4.,  30.,  67.,
        27.,  90.,  91.,   5.,  18.,  20.,  49.,  47.,  15.,  56.,  38.,
        88.,   7.])

## Handling CPP Marks

In [92]:
df["cpp_marks"].unique()

array([  0.,  31.,  nan,  20.,  79.,  61.,  37.,  96.,  42.,   8.,  71.,
        12.,  76.,  72.,  54.,  10.,  15.,  43.,  59.,   1.,  88.,  69.,
        67.,  24.,  66.,  14.,  28.,  95.,  52.,  94.,  29.,  56.,   4.,
        17.,  50.,  44.,  73.,  21.,  91.,  63.,  85.,  11.,  34.,  55.,
         7.,  64.,   5.,  35.,  58.,  39.,  81.,  13.,  90.,  70.,  65.,
        84.,  36.,  77.,  99.,  80.,  38.,  18.,  16.,  87.,  46.,  98.,
        75.,   3.,  83.,  53.,  62.,  23.,  40.,  93.,  30.,   6.,   2.,
        47.,  86.,  57.,  27.,  89.,  78.,  82.,   9.,  51.,  22.,  25.,
        19.,  74.,  97.,  33.,  48., 100.,  45.,  92.,  68.,  60.,  26.,
        32.,  41.,  49.])

In [93]:
df["cpp_marks"].dtypes

dtype('float64')

In [94]:
num = [65, 55, 54, 76, 45, 59, 72, 75, 85]

cpp_mask = (df["cpp_marks"] > 100) | (df["cpp_marks"].isna())
count = cpp_mask.sum()

repeated_nums = np.resize(num, count)

df.loc[cpp_mask, "cpp_marks"] = repeated_nums

## Handling SQL Marks

In [102]:
df["sql_marks"].unique()

array([0, nan, '99', '91', '?', '15', '-47', '7', '125', '86', '102',
       '114', '101', '25', '95', '-1', '48', '92', '45', '70', '53',
       '-25', '30', '-39', '94', '71', '-42', '63', '119', '-35', '38',
       '-40', '-10', '134', '17', '121', '39', '123', '57', '35', '61',
       '111', '49', '-31', '31', '141', '-11', '-49', '-43', '66', '136',
       '12', '-34', '72', '40', '28', '93', '131', '6', '128', '69', '8',
       '79', '116', '18', '77', '87', '33', '122', '85', '-18', '-3',
       '50', '3', '105', '11', '19', '139', '-29', '43', '115', '24',
       '117', '26', '127', '103', '-12', '150', '132', '-20', '44', '-27',
       '97', '143', '14', '133', '5', '-23', '-24', '112', '-30', '0',
       '109', '74', '27', '64', '-45', '-21', '16', '36', '22', '84',
       '-22', '-14', '29', '54', '-2', '-41', '144', '135', '130', '2',
       '58', '-32', '83', '-36', '47', '23', '107', '59', '108', '138',
       '75', '76', '42', '140', '-26', '137', '126', '106', '62', '68

In [103]:
df.loc[df["sql_marks"] == "?", "sql_marks"] = np.nan

In [104]:
df["sql_marks"].unique()

array([0, nan, '99', '91', '15', '-47', '7', '125', '86', '102', '114',
       '101', '25', '95', '-1', '48', '92', '45', '70', '53', '-25', '30',
       '-39', '94', '71', '-42', '63', '119', '-35', '38', '-40', '-10',
       '134', '17', '121', '39', '123', '57', '35', '61', '111', '49',
       '-31', '31', '141', '-11', '-49', '-43', '66', '136', '12', '-34',
       '72', '40', '28', '93', '131', '6', '128', '69', '8', '79', '116',
       '18', '77', '87', '33', '122', '85', '-18', '-3', '50', '3', '105',
       '11', '19', '139', '-29', '43', '115', '24', '117', '26', '127',
       '103', '-12', '150', '132', '-20', '44', '-27', '97', '143', '14',
       '133', '5', '-23', '-24', '112', '-30', '0', '109', '74', '27',
       '64', '-45', '-21', '16', '36', '22', '84', '-22', '-14', '29',
       '54', '-2', '-41', '144', '135', '130', '2', '58', '-32', '83',
       '-36', '47', '23', '107', '59', '108', '138', '75', '76', '42',
       '140', '-26', '137', '126', '106', '62', '68', '1

In [105]:
df["sql_marks"] = pd.to_numeric(df["sql_marks"], errors = "coerce")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\228802652.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sql_marks"] = pd.to_numeric(df["sql_marks"], errors = "coerce")


In [106]:
df.loc[df["sql_marks"] < 0, "sql_marks"] = np.nan

In [107]:
num = [65, 55, 54, 76, 45, 59, 72, 75, 85]

sql_mask = (df["sql_marks"] > 100) | (df["sql_marks"].isna())
count = sql_mask.sum()

repeated_nums = np.resize(num, count)

df.loc[sql_mask, "sql_marks"] = repeated_nums

In [108]:
df["sql_marks"].unique()

array([  0.,  65.,  55.,  99.,  54.,  76.,  91.,  45.,  15.,  59.,  72.,
        75.,  85.,   7.,  86.,  25.,  95.,  48.,  92.,  70.,  53.,  30.,
        94.,  71.,  63.,  38.,  17.,  39.,  57.,  35.,  61.,  49.,  31.,
        66.,  12.,  40.,  28.,  93.,   6.,  69.,   8.,  79.,  18.,  77.,
        87.,  33.,  50.,   3.,  11.,  19.,  43.,  24.,  26.,  44.,  97.,
        14.,   5.,  74.,  27.,  64.,  16.,  36.,  22.,  84.,  29.,   2.,
        58.,  83.,  47.,  23.,  42.,  62.,  68., 100.,  82.,  73.,  96.,
        20.,  46.,  88.,   1.,  52.,  13.,  60.,   4.,  10.,  51.,  41.,
        56.,  89.,  34.,  80.,  67.,  21.,  98.,  78.])

## Handling City Column

In [109]:
df["city"].unique()

array([0, 'nan', 'west lancebury', '123city', 'gilbertchester',
       'west larry', 'south kaitlyn', 'raymondchester', 'burnston',
       'daughertyfort', 'sheilamouth', 'lake stacey', 'robertview',
       'port stephanie', 'williamston', 'wilcoxshire', 'garciastad',
       'ericville', 'williamsfurt', 'lake charleston', 'markborough',
       'robertsport', 'east karenburgh', 'west johnny', 'parkerburgh',
       'port ashleymouth', 'chapmanton', 'north dylanville',
       'hillborough', 'east keith', 'watsontown', 'west mariashire',
       'allisonmouth', 'new tiffany', 'west james', 'east ann',
       'hannahfort', 'new samuelfort', 'north crystal', 'new josephport',
       'lake david', 'brentburgh', 'lawrenceborough', 'new austinview',
       'kristinaville', 'jasonton', 'anthonytown', 'hudsonborough',
       'sullivanport', 'west matthew', 'west kimberlyside', 'port julie',
       'grayfort', 'robinsonbury', 'millerview', 'new phyllischester',
       'robertfort', 'port christophe

In [111]:
df["city"].astype(str).str.lower().str.strip()

0                    0
1                  nan
3                  nan
4                    0
5                  nan
             ...      
2995               nan
2996                 0
2997    west susanberg
2998               nan
2999      dixonborough
Name: city, Length: 2815, dtype: object

In [144]:
def remove(name):
    if pd.isna(name):
        return np.nan

    name = str(name).strip().lower()

    if name == "0":
        return np.nan

    if "123" in name:
        parts = name.split("123")
        if len(parts) > 1:
            return parts[1]

    return name

df["city"] = df["city"].apply(remove)


C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\3365950500.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"] = df["city"].apply(remove)


In [162]:
import numpy as np

# Cities to fill
cities_to_fill = ["hudsonborough", "west lancebury", "new samuelfort"]

# Unwanted values
unwanted = ["Multan", "Peshawar", "Quetta"]

# Mask: rows jahan value unwanted, number, or empty string
mask = df["city"].apply(lambda x: str(x).strip().lower() in unwanted or str(x).isdigit() or str(x).strip() == "")

# Fill those rows with repeated cities_to_fill
df.loc[mask, "city"] = np.resize(cities_to_fill, mask.sum())

In [168]:
# Unwanted cities
unwanted = ["Multan", "Peshawar", "Quetta"]

# Replace with "hudsonborough"
df.loc[df["city"].isin(unwanted), "city"] = "hudsonborough"

In [169]:
df["city"].unique()

array(['hudsonborough', 'new samuelfort', 'lake charleston', 'west larry',
       'west lancebury', 'gilbertchester', 'south kaitlyn',
       'raymondchester', 'burnston', 'daughertyfort', 'sheilamouth',
       'lake stacey', 'robertview', 'port stephanie', 'williamston',
       'wilcoxshire', 'garciastad', 'ericville', 'williamsfurt',
       'markborough', 'robertsport', 'east karenburgh', 'west johnny',
       'parkerburgh', 'port ashleymouth', 'chapmanton',
       'north dylanville', 'hillborough', 'east keith', 'watsontown',
       'west mariashire', 'allisonmouth', 'new tiffany', 'west james',
       'east ann', 'hannahfort', 'north crystal', 'new josephport',
       'lake david', 'brentburgh', 'lawrenceborough', 'new austinview',
       'kristinaville', 'jasonton', 'anthonytown', 'sullivanport',
       'west matthew', 'west kimberlyside', 'port julie', 'grayfort',
       'robinsonbury', 'millerview', 'new phyllischester', 'robertfort',
       'port christophermouth', 'lindaville'

## Handling Date Columns

In [122]:
df.head()

student_id        student_name father_name   gender    age class  \
0           0                   0           0        0    0.0     0   
1           1  christopher turner  gary davis  unknown   22.0  bscs   
3           3             unknown       ffill     male  200.0  10th   
4           0                   0           0        0    0.0     0   
5           5       tabitha payne         nan   female  200.0  bscs   

   python_marks  java_marks  ruby_marks  cpp_marks  sql_marks city  \
0           0.0         0.0         0.0        0.0        0.0  nan   
1          55.0        44.0        17.0       31.0       65.0  nan   
3          80.0        54.0         8.0       65.0       55.0  nan   
4           0.0         0.0         0.0        0.0        0.0  nan   
5          54.0        74.0        65.0       55.0       99.0  nan   

  admission_date  
0              0  
1     06/05/2022  
3     1994-09-06  
4              0  
5            NaN

In [123]:
df["admission_date"].unique()

array([0, '06/05/2022', '1994-09-06', ..., 'March 17, 2024', '2002-12-30',
       '11/05/2025'], shape=(1171,), dtype=object)

In [124]:
df["admission_date"] = df["admission_date"].replace(
    r"^\s*$",  # empty OR spaces only
    np.nan,
    regex=True
)

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\2576123468.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["admission_date"] = df["admission_date"].replace(


In [125]:
df["admission_date"] = (df["admission_date"].astype(str).str.strip().str.replace(".","/", regex = False))

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\3102947554.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["admission_date"] = (df["admission_date"].astype(str).str.strip().str.replace(".","/", regex = False))


In [126]:
df["admission_date"]

0                     0
1            06/05/2022
3            1994-09-06
4                     0
5                   nan
             ...       
2995         2023/09/03
2996                  0
2997    August 06, 2023
2998         11/05/2025
2999                nan
Name: admission_date, Length: 2815, dtype: object

In [127]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [128]:
df["admission_date"] = pd.to_datetime(df["admission_date"], errors = "coerce")

C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\1612628951.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["admission_date"] = pd.to_datetime(df["admission_date"], errors = "coerce")
C:\Users\AL AYESHA COMPUTER\AppData\Local\Temp\ipykernel_9484\1612628951.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["admission_date"] = pd.to_datetime(df["admission_date"], errors = "coerce")


In [129]:
mask = df["admission_date"].isna()
df.loc[mask, "admission_date"] = pd.to_datetime(
    df.loc[mask, "admission_date"],
    dayfirst=True,
    errors="coerce"
)

In [130]:
df["admission_date"].unique()

<DatetimeArray>
[                'NaT', '2022-06-05 00:00:00', '1994-09-06 00:00:00',
 '2022-12-02 00:00:00', '1989-12-08 00:00:00', '1971-12-23 00:00:00',
 '2021-11-12 00:00:00', '2022-02-12 00:00:00', '1977-09-05 00:00:00',
 '2024-12-24 00:00:00',
 ...
 '2022-08-05 00:00:00', '2021-05-19 00:00:00', '2007-02-23 00:00:00',
 '2012-01-14 00:00:00', '2025-01-05 00:00:00', '2024-08-07 00:00:00',
 '2022-10-27 00:00:00', '2024-03-17 00:00:00', '2002-12-30 00:00:00',
 '2025-11-05 00:00:00']
Length: 1023, dtype: datetime64[ns]

In [561]:
df["admission_date"].dtype

dtype('<M8[ns]')

In [131]:
df[df["gender"] == 20]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []

In [132]:
df["admission_date"].ffill().bfill()

0      2022-06-05
1      2022-06-05
3      1994-09-06
4      1994-09-06
5      1994-09-06
          ...    
2995   2023-09-03
2996   2023-09-03
2997   2023-08-06
2998   2025-11-05
2999   2025-11-05
Name: admission_date, Length: 2815, dtype: datetime64[ns]

In [174]:
df.head()

student_id        student_name father_name   gender    age class  \
0           0                   0           0        0    0.0     0   
1           1  christopher turner  gary davis  unknown   22.0  bscs   
3           3             unknown  gary davis     male  200.0  10th   
4           0                   0           0        0    0.0     0   
5           5       tabitha payne         nan   female  200.0  bscs   

   python_marks  java_marks  ruby_marks  cpp_marks  sql_marks  \
0           0.0         0.0         0.0        0.0        0.0   
1          55.0        44.0        17.0       31.0       65.0   
3          80.0        54.0         8.0       65.0       55.0   
4           0.0         0.0         0.0        0.0        0.0   
5          54.0        74.0        65.0       55.0       99.0   

              city admission_date  
0    hudsonborough            NaT  
1   new samuelfort     2022-06-05  
3  lake charleston     1994-09-06  
4       west larry            NaT  
5    hudsonborough            NaT

## Handling Class Columns

In [170]:
df[df["city"] == "nan"]

Empty DataFrame
Columns: [student_id, student_name, father_name, gender, age, class, python_marks, java_marks, ruby_marks, cpp_marks, sql_marks, city, admission_date]
Index: []